script: cat /dev/null
deploy:
  provider: s3
  access_key_id:
    secure: T1bCb1/XwJWfggFR2illL6k7aV/CoJWqfQespvgFmrLk+u5ijvOWWG4NA1hb06TOUyKUd6bvT5e/7lwNMddtmXQzBuavrag7YsxCCrOuB/b+ux0ohB/16Qgi3zkLAVsnNs8vYBdt8DDRV/OPV3iQR8c/pcY/PFyRpuqjU3z3WGrlT63lsDT7uogOyT4XTWPois5r5c4SkHpViw37qY9WU++T87ZdSeE8n2zOjkI2w47sCcY1rMgHdA7jkYNj9WxSrhPkJXGD1DUqf8aga/4PlZ6P85707qk9Pv0TLkj1Ssc96P/A9gRRsW0qSq2sk40aGC1tiMW6OZT5PJn/JNiVnWYUhWbbsj8SgV/9liwBn7+8gLp5Qge4sbqUlg9qsZZFE7GFOlCZsEvc530oHbXZTcdTMnZ5VqQkmfAbG36fM2sbntteBapd4M5+tnHswR6e0LQ4EHvGEzswvntuDQsbImwds5+IlLQBPs3h//SkJLjmgUOtwtSB44tdtfOMU98XAnJbiQhJWZ5BiS6XnVYpv6U/lSjmPA+zjKvjnQ+so4kfF55p+l56AQnUfzqFU0ruDk0Co9Ke0c/ZnjDKAu1DQwbbl3nCqiQSk7JLwik9enpIXCCZ7egmCtrNf6TDAEaaFWOv4J0kYHCBgz2nATDJoKso3qjlm6sMXBi7W5LoXcY=
  secret_access_key:
    secure: NhfhAJ1MPK9F3jx3tZ+ZTlY4zxV0LEmAdaPYQvs+6swLKPiHd5SkX8E/pXrz1SuNRcxWgMxx5H+KRyUwBeiGmAXzV0rQfusgHDIeqcOvQDve/2f++xk+IqGvkPWCJwPuMdrrPpdcwbpLjVYT16iLjOSqWD3D0Arh7at9Ahf28w1dXkTZNtTk/MWUXb6JqxJ/YBy0eyBHvLbCGqH4lU4031LoZotG66aWYzY09DVZSqHIHiA50VpvgSWz8QwVXrVvj7hMTamoZPJP8lKJ+jluRTnGaZEc2zEiOUf4sP4aoskDsP1Tftd+JByQKkz15Cj94/yl+v1wHsvdZsfW5uUuPsuhboHpR9yVh1fbROfPlS98a6ZycZZKpPkN25SQJAa+M/0ZMbfxwgvW5c2cjYKqkm+HNwkEwDXrQmWezqD0ud2ousAOb4A/67BPk6So3b8kMmUiYOyykfJvmumWkhk8s9xo6pSwBJJIUKO6++DZqwX4kwoSoX2Or3KtM2IVOWsCoJvXHU0ryNsdEPaJo24DjazPpEQ46UVQSTjFnmJPl4+6zIxG7mZuZNfqcMDyN1mBlTbpDIsTFSs5YpJL6+AUiq5vswNmhsL6rkAOHvOqLYeAcKTIn+yKv5qNmOAn/XVVR0KlzAD9UB706l7XpR3CoaGy2UVyh0PWrGqCVE8Q0zE=
  bucket: init.yaktor.io
  skip_cleanup: true
  acl: public_read

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/b3322e3bfdacd5e58db4
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
